-- BLOCK select_recent_images
SELECT *
FROM (
    VALUES
    ('alawini/cs411-neo4j'),
    ('alawini/cs411-sql:latest'),
    ('altonb/centos7-rpy'),
    ('altonb/ubuntu-pyspark'),
    ('bowmannat/javagrader'),
    ('cs125/quiz:0.0.21'),
    ('cs125/quiz:0.0.22'),
    ('cs125/quiz:0.1.9'),
    ('cs125/quiz:latest'),
    ('dowobeha/docker-ubuntu-foma'),
    ('eecarrier/c-and-python-v2'),
    ('liquidh2/cs427fa18debugging'),
    ('liquidh2/cs427fa18testing'),
    ('mattox/clojure-prairielearn'),
    ('mattox/haskell-prairielearn'),
    ('mysql-test:latest'),
    ('nicknytko/cs199-grader:1.0.0'),
    ('prairielearn/centos7-base'),
    ('prairielearn/centos7-base:dev'),
    ('prairielearn/centos7-cs225'),
    ('prairielearn/centos7-cs418:latest'),
    ('prairielearn/centos7-java'),
    ('prairielearn/centos7-ocaml'),
    ('prairielearn/centos7-python'),
    ('prairielearn/centos7-verilog'),
    ('prairielearn/grader-python'),
    ('prairielearn/grader-r'),
    ('rahulr2/cs296-25-docker-image'),
    ('stat430/pl'),
    ('yrliu/centos7-ece220:v1'),
    ('zmabry2/cs196-autograde')
) AS q(external_grading_image);
