properties:
  # How many grading jobs should run at once
  maxConcurrentJobs:
    default: 5
    envVar: MAX_CONCURRENT_JOBS

  # Feature enable/disable
  useDatabase:
    default: false
    envVar: USE_DATABASE
  useEc2MetadataService:
    default: true
    envVar: USE_EC2_METADATA_SERVICE
  useCloudWatchLogging:
    default: false
    envVar: USE_CLOUDWATCH_LOGGING
  useConsoleLoggingForJobs:
    default: false
    envVar: USE_CONSOLE_LOGGING_FOR_JOBS
  # Controls which log levels are printed for the global logger
  globalLoggerLevel:
    default: info
    envVar: GLOBAL_LOGGER_LEVEL
  # Controls which log levels are printed for the individual job loggers
  jobLoggerLevel:
    default: info
    envVar: JOB_LOGGER_LEVEL
  useImagePreloading:
    default: false
    envVar: USE_IMAGE_PRELOADING
  useHealthCheck:
    default: true
    envVar: USE_HEALTH_CHECK

  # CloudWatch logging
  globalLogGroup:
    default: 'grading-instances-debug'
    envVar: GLOBAL_LOG_GROUP
  jobLogGroup:
    default: 'grading-jobs-debug'
    envVar: JOB_LOG_GROUP

  # Load reporting config
  reportLoad:
    default: false
    envVar: REPORT_LOAD
  reportIntervalSec:
    default: 10
    envVar: REPORT_INTERVAL_SEC

  # Health check config
  healthCheckPort:
    default: 4000
    envVar: HEALTH_CHECK_PORT
  healthCheckInterval: # In milliseconds
    default: 30000 # 30 seconds
    envVar: HEALTH_CHECK_INTERVAL

  # Queue config
  queueType:
    default: 'sqs'
    envVar: QUEUE_TYPE
  queueName:
    default: 'grading'
    envVar: QUEUE_NAME
  sqsQueueUrl:
    default: null
    envVar: SQS_QUEUE_URL
  rabbitMqHost:
    default: 'amqp://localhost'
    envVar: RABBITMQ_HOST
  defaultTimeout:
    default: 30
    envVar: DEFAULT_TIMEOUT

  # Where to get/store files
  # One of: s3, disk
  fileStoreType:
    default: 's3'
    envVar: FILE_STORE_TYPE
  fileStorePath:
    default: '/jobs'
    envVar: FILE_STORE_PATH

  # If this is set to something non-null, then PG will write the job files into
  # the path specified by `jobFilesVolumePath`, which is assumed to be the
  # mount location of the `jobFilesVolumeName` volume. When running the job
  # container, that volume will then be mounted as /grade.
  jobFilesVolumeName:
    default: null
    envVar: JOB_FILES_VOLUME_NAME
  jobFilesVolumePath:
    default: null
    envVar: JOB_FILES_VOLUME_PATH

  # Postgres config
  postgresqlHost:
    default: localhost
    envVar: PG_HOST
  postgresqlDatabase:
    default: postgres
    envVar: PG_DATABASE
  postgresqlUser:
    default: postgres
    envVar: PG_USER
  postgresqlPassword:
    default: null
    envVar: PG_PASSWORD
