properties:
  # How many grading jobs should run at once
  maxConcurrentJobs:
    default: 5
    envVar: MAX_CONCURRENT_JOBS

  # Feature enable/disable
  useDatabase:
    default: false
    envVar: USE_DATABASE
  useEc2MetadataService:
    default: true
    envVar: USE_EC2_METADATA_SERVICE
  useCloudWatchLogging:
    default: false
    envVar: USE_CLOUDWATCH_LOGGING
  useConsoleLoggingForJobs:
    default: false
    envVar: USE_CONSOLE_LOGGING_FOR_JOBS
  useImagePreloading:
    default: false
    envVar: USE_IMAGE_PRELOADING
  useHealthCheck:
    default: true
    envVar: USE_HEALTH_CHECK

  # CloudWatch logging
  globalLogGroup:
    default: 'grading-instances-debug'
    envVar: GLOBAL_LOG_GROUP
  jobLogGroup:
    default: 'grading-jobs-debug'
    envVar: JOB_LOG_GROUP

  # Load reporting config
  reportLoad:
    default: false
    envVar: REPORT_LOAD
  reportIntervalSec:
    default: 10
    envVar: REPORT_INTERVAL_SEC

  # Health check config
  healthCheckPort:
    default: 4000
    envVar: HEALTH_CHECK_PORT
  healthCheckInterval: # In milliseconds
    default: 30000 # 30 seconds
    envVar: HEALTH_CHECK_INTERVAL

  # Queue config
  queueName:
    default: 'grading'
    envVar: QUEUE_NAME
  queueUrl:
    default: null
    envVar: QUEUE_URL
  defaultTimeout:
    default: 30
    envVar: DEFAULT_TIMEOUT

  # Postgres config
  postgresqlHost:
    default: 'localhost'
    envVar: PG_HOST
  postgresqlDatabase:
    default: 'postgres'
    envVar: PG_DATABASE
  postgresqlUser:
    default: null
    envVar: PG_USER
  postgresqlPassword:
    default: null
    envVar: PG_PASSWORD
